#!/bin/bash
# Setup iniziale progetto - genera secrets e configura environment

set -e

echo "================================================"
echo "Linux Security AI - Setup Iniziale"
echo "================================================"
echo ""

# Check prerequisites
echo "Verifica prerequisiti..."

command -v python3 >/dev/null 2>&1 || { echo "❌ Python3 richiesto"; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "❌ Docker richiesto"; exit 1; }
command -v docker-compose >/dev/null 2>&1 || { echo "❌ Docker Compose richiesto"; exit 1; }

echo "✓ Prerequisiti OK"
echo ""

# Generate secrets
echo "Generazione secrets..."

API_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
AGENT_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
DASHBOARD_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
DB_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")

echo "✓ Secrets generati"
echo ""

# Create .env if not exists
if [ -f .env ]; then
    echo "⚠️  File .env già esistente"
    read -p "Sovrascrivere? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup annullato"
        exit 0
    fi
fi

echo "Creazione file .env..."

cat > .env << EOF
# ============================================
# Auto-generated by setup.sh
# Date: $(date)
# ============================================

# DATABASE
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://securityuser:\${DB_PASSWORD}@postgres:5432/security_monitoring

# API & AUTHENTICATION
API_SECRET_KEY=${API_SECRET}
JWT_SECRET=${JWT_SECRET}
AGENT_API_TOKEN=${AGENT_TOKEN}

# ENCRYPTION
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# DASHBOARD
DASHBOARD_SECRET_KEY=${DASHBOARD_SECRET}

# CHROMA VECTOR DB
CHROMA_HOST=chroma
CHROMA_PORT=8000

# LOGGING
LOG_LEVEL=INFO

# SECURITY POLICIES
DATA_RETENTION_DAYS=90
ALERT_RETENTION_DAYS=180
ENABLE_AUDIT_LOG=true

# AGENT CONFIGURATION
CENTRAL_SERVER_URL=https://central-server:8000
COLLECTION_INTERVAL=30

# ML SETTINGS
ANOMALY_THRESHOLD=0.7
MALWARE_THRESHOLD=0.8

# CORS
ALLOWED_ORIGINS=https://localhost:8443,https://dashboard:443

# EMBEDDING MODEL
EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2

# DEVELOPMENT
DEBUG_MODE=false
SKIP_SSL_VERIFY=false
EOF

echo "✓ File .env creato"
echo ""

# Generate SSL certificates
if [ ! -f certs/server-cert.pem ]; then
    echo "Generazione certificati SSL..."
    bash scripts/generate_certs.sh
else
    echo "✓ Certificati SSL già presenti"
fi

echo ""
echo "================================================"
echo "Setup Completato!"
echo "================================================"
echo ""
echo "📝 File generati:"
echo "  - .env (secrets e configurazione)"
echo "  - certs/server-key.pem"
echo "  - certs/server-cert.pem"
echo ""
echo "🔑 IMPORTANTE - Salva questi valori in modo sicuro:"
echo ""
echo "Agent API Token (da usare negli agent):"
echo "  ${AGENT_TOKEN}"
echo ""
echo "⚠️  NON committare .env su Git!"
echo ""
echo "📚 Prossimi passi:"
echo "  1. Rivedi configurazione in .env"
echo "  2. Avvia sistema: docker-compose up --build"
echo "  3. Verifica: curl http://localhost:8000/health"
echo "  4. Dashboard: https://localhost:8443"
echo ""
