#!/bin/bash
# Setup iniziale progetto - genera secrets e configura environment

set -e

echo "================================================"
echo "Linux Security AI - Setup Iniziale"
echo "================================================"
echo ""

# Check prerequisites
echo "Verifica prerequisiti..."

command -v python3 >/dev/null 2>&1 || { echo "❌ Python3 richiesto"; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "❌ Docker richiesto"; exit 1; }
command -v docker-compose >/dev/null 2>&1 || { echo "❌ Docker Compose richiesto"; exit 1; }

echo "✓ Prerequisiti OK"
echo ""

# Generate secrets
echo "Generazione secrets..."

API_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
AGENT_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
DASHBOARD_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
DB_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")

# Network / deployment defaults (override via env before running setup.sh)
SERVER_IP=${SERVER_IP:-127.0.0.1}
SERVER_API_PORT=${SERVER_API_PORT:-8000}
SERVER_DASHBOARD_HTTPS_PORT=${SERVER_DASHBOARD_HTTPS_PORT:-8443}

echo "✓ Secrets generati"
echo ""

# Create .env if not exists
if [ -f .env ]; then
    echo "⚠️  File .env già esistente"
    read -p "Sovrascrivere? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup annullato"
        exit 0
    fi
fi

echo "Creazione file .env..."

cat > .env << EOF
# ============================================
# Auto-generated by setup.sh
# Date: $(date)
# ============================================

# DATABASE
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://securityuser:\${DB_PASSWORD}@postgres:5432/security_monitoring

# API & AUTHENTICATION
API_SECRET_KEY=${API_SECRET}
JWT_SECRET=${JWT_SECRET}
AGENT_API_TOKEN=${AGENT_TOKEN}

# ENCRYPTION
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# DASHBOARD
DASHBOARD_SECRET_KEY=${DASHBOARD_SECRET}

# CHROMA VECTOR DB
CHROMA_HOST=chroma
CHROMA_PORT=8000

# LOGGING
LOG_LEVEL=INFO

# SECURITY POLICIES
DATA_RETENTION_DAYS=90
ALERT_RETENTION_DAYS=180
ENABLE_AUDIT_LOG=true

# AGENT CONFIGURATION
CENTRAL_SERVER_URL=http://${SERVER_IP}:${SERVER_API_PORT}
COLLECTION_INTERVAL=30

# ML SETTINGS
ANOMALY_THRESHOLD=0.7
MALWARE_THRESHOLD=0.8

# CORS
ALLOWED_ORIGINS=https://${SERVER_IP}:${SERVER_DASHBOARD_HTTPS_PORT},https://dashboard:443

# EMBEDDING MODEL
EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2

# DEVELOPMENT
DEBUG_MODE=false
SKIP_SSL_VERIFY=false
EOF

echo "✓ File .env creato"
echo ""

echo "Creazione file .env.server e .env.client per deployment distribuito..."

cat > .env.server << EOF
# ============================================
# Auto-generated by setup.sh
# Date: $(date)
# ============================================
POSTGRES_USER=securityuser
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=security_monitoring
POSTGRES_PORT=5432

CHROMA_PUBLIC_PORT=8001
API_PUBLIC_PORT=${SERVER_API_PORT}
DASHBOARD_HTTP_PORT=8081
DASHBOARD_HTTPS_PORT=${SERVER_DASHBOARD_HTTPS_PORT}

API_TOKEN=${AGENT_TOKEN}
API_SECRET_KEY=${API_SECRET}
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
FLASK_SECRET_KEY=${DASHBOARD_SECRET}

ALLOWED_ORIGINS=http://${SERVER_IP}:${SERVER_DASHBOARD_HTTPS_PORT}
LOG_LEVEL=INFO
EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
EOF

cat > .env.client << EOF
# ============================================
# Auto-generated by setup.sh
# Date: $(date)
# ============================================
CENTRAL_SERVER_URL=http://${SERVER_IP}:${SERVER_API_PORT}
API_TOKEN=${AGENT_TOKEN}
HOST_ID=client-host-001
COLLECTION_INTERVAL=30

# Code scanner options (profile: scan)
SCAN_TARGET=/workspace/to_scan
SCAN_TARGET_HOST=./

# Malware agent options (profile: malware)
MALWARE_SCAN_PATH=/workspace/to_scan
MALWARE_SCAN_INTERVAL=300

# IDS options (profile: ids)
IDS_INTERVAL=30
IDS_LOG_FILE=/var/log/auth.log
IDS_LOG_FILE_HOST=/var/log/auth.log
EOF

echo "✓ File .env.server e .env.client creati"
echo ""

# Generate SSL certificates
if [ ! -f certs/server-cert.pem ]; then
    echo "Generazione certificati SSL..."
    bash scripts/generate_certs.sh
else
    echo "✓ Certificati SSL già presenti"
fi

echo ""
echo "================================================"
echo "Setup Completato!"
echo "================================================"
echo ""
echo "📝 File generati:"
echo "  - .env (secrets e configurazione)"
echo "  - .env.server (docker-compose.server.yml)"
echo "  - .env.client (docker-compose.client.yml)"
echo "  - certs/server-key.pem"
echo "  - certs/server-cert.pem"
echo ""
echo "🔑 IMPORTANTE - Salva questi valori in modo sicuro:"
echo ""
echo "Agent API Token (da usare negli agent):"
echo "  ${AGENT_TOKEN}"
echo ""
echo "⚠️  NON committare .env su Git!"
echo ""
echo "📚 Prossimi passi:"
echo "  1. Rivedi configurazione in .env"
echo "  2. (Server) docker compose -f docker-compose.server.yml --env-file .env.server up -d --build"
echo "  3. (Client) docker compose -f docker-compose.client.yml --env-file .env.client up -d"
echo "  4. Verifica: curl http://${SERVER_IP}:${SERVER_API_PORT}/health"
echo "  5. Dashboard: https://${SERVER_IP}:${SERVER_DASHBOARD_HTTPS_PORT}"
echo ""
